name: نشر موقع Jekyll تلقائيًا

on:
  push:
    branches:
      - main  # تأكد أن الفرع الرئيسي هو 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: استنساخ المستودع
        uses: actions/checkout@v3

      - name: إعداد Ruby و Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: تثبيت Jekyll والاعتماديات
        run: |
          gem install bundler
          bundle install

      - name: بناء الموقع باستخدام Jekyll
        run: bundle exec jekyll build

      - name: نشر الموقع إلى GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # الفرع الذي سيتم نشر الموقع فيه
          folder: _site  # تأكد أن هذا هو مجلد الإخراج لـ Jekyll
